#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BFCAndroid.Resource", IsApplication=true)]

namespace BFCAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int addProblemButton = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int appMethodsSpinner = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int boomHeightSpinner = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int editText1 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int editText2 = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int filterEditText = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int labelSpraySpinner = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int sprayQualitySpinner = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050012
			public const int textView10 = 2131034130;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int textView3 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int textView4 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int textView5 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int textView6 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textView7 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int textView8 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int textView9 = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int windSpeedSpinner = 2131034124;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SelectItem = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
